config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'export', on: :collection
    get 'datatables_index_role', on: :collection # Displays users for showed role
    patch 'account_off', on: :member
    patch 'account_on', on: :member
  end

  resources :roles do
    get 'export', on: :collection
    get 'datatables_index_user', on: :collection # Displays roles for showed user
    resources :users, only: [:create, :destroy], controller: 'roles/users'
  end    

  resources :surveys do
    get 'export', on: :collection
    get 'send_score', on: :collection 
    get 'show_score', on: :collection 
  end

  resources :works, only: [:index] do
    post 'datatables_index', on: :collection # for User
    post 'datatables_index_trackable', on: :collection # for Trackable
    post 'datatables_index_user', on: :collection # for User
  end

  resources :charts, only: [] do
    get 'departments_by_question_pie', on: :collection
    get 'departments_by_question_column', on: :collection
    get 'departments_sum_pie', on: :collection
    get 'departments_sum_column', on: :collection
    get 'point_files', on: :collection
    get 'xml_miejsce_realizacji_tables', on: :collection
  end

  resources :expositions, except: [:show, :edit, :update]

  get 'datatables/lang'

  get 'static_pages/home'
  get 'static_pages/introduction'
  get 'static_pages/job_1'
  get 'static_pages/job_2'
  get 'static_pages/job_3'
  get 'static_pages/job_4'
  get 'static_pages/job_5'

  root to: 'static_pages#home'

end

app/controllers/roles/users_controller.rb
class Roles::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 
    role.users << user if role.present? && user.present?
    head :ok
  end

  def destroy
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 
    user.roles.delete(role) if role.present? && user.present?
    head :no_content
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  def after_resetting_password_path_for(resource)
    Work.create!(trackable: resource, trackable_url: "#{user_path(resource)}", action: 'resetting_password_from_token', user: resource, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: resource.id, name: resource.name, email: resource.email, notice: request.flash["notice"]}.to_json)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    Work.create!(trackable: resource, trackable_url: "#{user_path(resource)}", action: 'sending_reset_password_instructions', user: resource, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: resource.id, name: resource.name, email: resource.email, notice: request.flash["notice"]}.to_json)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # PUT /resource
  # def update
  #   # required for settings form to submit when esod_password is blank
  #   if params[:user][:esod_password].blank?
  #      params[:user].delete(:esod_password)
  #   end
  #   super
  # end


  def update
    # add
    if params[:user][:esod_password].blank?
      params[:user].delete(:esod_password)
    end
    #
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      # add
      resource.log_work('update', current_user.id)
      #
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy  
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end  

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end


  # If the account that is registered is confirmable and not active yet, 
  # you have to override after_inactive_sign_up_path_for method.
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_inactive_sign_up_path_for(resource)
    Work.create!(trackable: resource, trackable_url: "#{user_path(resource)}", action: 'sign_up', user: resource, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: resource.id, name: resource.name, email: resource.email, notice: request.flash["notice"]}.to_json)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  # respond_to :json
  # dodanie powyższego umożliwia zalogowanie się z cUrla
  # curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST $ROOT_URL/users/sign_in -d '{"user":{"email":"a.wojcieszek@uke.gov.pl","password":"1qazXSW@"}}'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  # POST /resource/sign_in
  def create
    super
    # Jeżeli udane logowanie, to zapisz do historii
    Work.create!(trackable: current_user, trackable_url: "#{user_path(current_user)}", action: 'sign_in', user: current_user, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: current_user.id, name: current_user.name, email: current_user.email, notice: request.flash["notice"]}.to_json)

  end

  # DELETE /resource/sign_out
  def destroy
    u = current_user
    super
    # Jeżeli udane wylogowanie, to zapisz do historii
    Work.create!(trackable: u, trackable_url: "#{user_path(u)}", action: 'sign_out', user: u, parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: u.id, name: u.name, email: u.email, notice: request.flash["notice"]}.to_json)
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    Work.create!(trackable: resource, trackable_url: "#{user_path(resource)}", action: 'sending_unlock_instructions', user: resource, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: resource.id, name: resource.name, email: resource.email, notice: request.flash["notice"]}.to_json)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    Work.create!(trackable: resource, trackable_url: "#{user_path(resource)}", action: 'unlocking_from_token', user: resource, 
      parameters: {remote_ip: request.remote_ip, fullpath: request.fullpath, id: resource.id, name: resource.name, email: resource.email, notice: request.flash["notice"]}.to_json)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index_role]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :account_off, :account_on]


  def export
    authorize :user, :index?
    @data = User.where.not(department_id: [1]).order(:name).all
    respond_to do |format|
      format.csv { send_data @data.to_csv, filename: "warsztay_rsp_users_#{Time.zone.today.strftime("%Y-%m-%d")}.csv" }
    end
  end

  # GET /users
  # GET /users.json
  def index
    authorize :user, :index?
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(params) }
    end
  end

  def datatables_index_role
    respond_to do |format|
      format.json{ render json: RoleUsersDatatable.new(params, only_for_current_role_id: params[:role_id] ) }
    end
  end

  def select2_index
    authorize :user, :index?
    #params[:q] = (params[:q]).upcase
    params[:q] = params[:q]
    @users = User.order(:name).finder_user(params[:q])
    @users_on_page = @users.page(params[:page]).per(params[:page_limit])
    
    render json: { 
      users: @users_on_page.as_json(methods: :fullname, only: [:id, :fullname]),
      meta: { total_count: @users.count }  
    } 
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user, :show?
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user, :new?
  end

  # GET /users/1/edit
  def edit
    authorize @user, :edit?
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user, :create?
    respond_to do |format|
      if @user.save
        flash[:success] = t('activerecord.successfull.messages.created', data: @user.fullname)
        @user.log_work('create', current_user.id)
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user, :update?
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = t('activerecord.successfull.messages.updated', data: @user.fullname)
        @user.log_work('update', current_user.id)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    # @user.destroy
    # respond_to do |format|
    #   flash[:success] = "User destroyed!"
    #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    authorize @user, :destroy?
    if @user.destroy
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @user.fullname)
      redirect_to users_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @user.fullname)
      #redirect_to :back
      render :show
    end      
  end

  def account_off
    authorize @user, :update?

    @user.soft_delete
    if @user.save
      flash[:success] = t('activerecord.successfull.messages.account_off', data: @user.fullname)
      redirect_to @user
    else 
      flash.now[:error] = t('activerecord.errors.messages.account_off', data: @user.fullname)
      render :show 
    end         
  end

  def account_on
    authorize @user, :update?

    @user.deleted_at = nil
    if @user.save
      flash[:success] = t('activerecord.successfull.messages.account_on', data: @user.fullname)
      redirect_to @user
    else 
      flash.now[:error] = t('activerecord.errors.messages.account_on', data: @user.fullname)
      render :show 
    end         
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :department_id, :position, :note, :photo)
    end
end

app/views/users/_data.html.erb
<div class="col-sm-11 col-sm-offset-1">
  <% input_disabled ||= false  
     #if input_disabled is not passed to the partial it doesn't crash. 
     # We default it to false 
  %>

  <%= form_errors_for @user %>

  <div class="row">
    <div class="col-sm-6">
      <div class="row">

        <div class="form-group col-sm-6">
          <p><strong><%= User.human_attribute_name(:name) %></strong></p>
          <%= @user.name %>
        </div>

        <div class="form-group col-sm-6">
          <p><strong><%= User.human_attribute_name(:email) %></strong></p>
          <%= @user.email %>
        </div>

        <div class="form-group col-sm-12">
          <p><strong><%= User.human_attribute_name(:department) %></strong></p>
          <%= @user.department.name %>
        </div>

        <div class="form-group col-sm-12">
          <p><strong><%= User.human_attribute_name(:position) %></strong></p>
          <%= @user.position %>
        </div>

      </div>  <!-- /row -->
    </div>  <!-- /col-sm-6 -->

    <div class="col-sm-6">
      <div class="row">
        <div class="form-group col-sm-12">
<!-- 
          <%#= image_tag(@user.photo) if @user.photo.attached? %>

 -->          <%= image_tag(@user.photo.variant(resize: "150x150")) if @user.photo.attached? %>
        </div>

        <div class="form-group col-sm-12">
          <p><strong><%= User.human_attribute_name(:note) %></strong></p>
          <%= text_with_break_line(@user.note) %>
        </div>
      </div>
    </div> <!--/col-sm-6 -->
  </div>  <!-- /row -->

  <div class="row">
    <div class="col-sm-12">
      <div class="row">

        <div class="form-group col-sm-3">
          <p><strong><%= User.human_attribute_name(:last_sign_in_at) %></strong></p>
          <%= @user.last_sign_in_at.strftime("%Y-%m-%d %H:%M:%S") if @user.last_sign_in_at.present? %>
        </div>
        <div class="form-group col-sm-3">
          <p><strong><%= User.human_attribute_name(:last_sign_in_ip) %></strong></p>
          <%= @user.last_sign_in_ip if @user.last_sign_in_ip.present? %>
        </div>

        <div class="form-group col-sm-3">
          <p><strong><%= User.human_attribute_name(:current_sign_in_at) %></strong></p>
          <%= @user.current_sign_in_at.strftime("%Y-%m-%d %H:%M:%S") if @user.current_sign_in_at.present? %>
        </div>
        <div class="form-group col-sm-3">
          <p><strong><%= User.human_attribute_name(:current_sign_in_ip) %></strong></p>
          <%= @user.current_sign_in_ip if @user.current_sign_in_ip.present? %>
        </div>

      </div>

    </div> <!-- /col-sm-12 -->
  </div> <!-- /row -->

  <div class="row">
    <div class="col-sm-12">

      <div class="row">
        <div class="form-group col-sm-3">
          <p><strong><%= User.human_attribute_name(:deleted_at) %></strong></p>
          <h5><%= @user.deleted_at.strftime("%Y-%m-%d %H:%M:%S") if @user.deleted_at.present? %></h5>
        </div>

        <div class="form-group col-sm-3">
          <p><strong><%#= User.human_attribute_name(:last_activity_at) %></strong></p>
          <h5><%#= @user.last_activity_at.strftime("%Y-%m-%d %H:%M:%S") if @user.last_activity_at.present? %></h5>
        </div>

        <div class="form-group col-sm-3">
          <p><strong><%#= User.human_attribute_name(:password_changed_at) %></strong></p>
          <h5><%#= @user.password_changed_at.strftime("%Y-%m-%d %H:%M:%S") if @user.password_changed_at.present? %></h5>
        </div>

      </div>

    </div> <!-- /col-sm-12 -->
  </div> <!-- /row -->

  <hr class="hr-without-top-margin">

  <% if input_disabled %>
    <!-- for "Show" -->
    <div class="row">

      <%= link_to users_path, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-th-list"></span>
        <%= t("helpers.links.index") %>
      <% end %>

      <% if policy(@user).destroy? %>
        <%= link_to user_path(@user),
                            method: :delete,
                            data: { confirm: t('helpers.links.confirm_destroy', data: @user.name) }, 
                            class: "btn btn-danger" do %>
          <span class="glyphicon glyphicon-trash"></span>
          <%= t("helpers.links.destroy") %>
        <% end %>
      <% end %>

      <% if policy(@user).edit? %>
        <%= link_to edit_user_path(@user), class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-edit"></span>
          <%= t("helpers.links.edit") %>
        <% end %>

        <% if @user.deleted_at.present? %>
          <%= link_to account_on_user_path(@user),
                              method: :patch,
                              data: { confirm: t('helpers.links.confirm_account_on', data: @user.fullname) }, 
                              class: "btn btn-warning" do %>
            <span class="glyphicon glyphicon-unlock"></span>
            <%= t("helpers.links.account_on") %>
          <% end %>
        <% else %>
          <%= link_to account_off_user_path(@user),
                              method: :patch,
                              data: { confirm: t('helpers.links.confirm_account_off', data: @user.fullname) }, 
                              class: "btn btn-warning" do %>
            <span class="glyphicon glyphicon-lock"></span>
            <%= t("helpers.links.account_off") %>
          <% end %>
        <% end %>

      <% end %>

    </div> <!-- /row -->
  <% else %>
    <!-- form "New"/"Edit" -->
  <% end %>

</div> <!--/col-sm-11 col-sm-offset-1-->    

app/views/users/_form.html.erb
<div class="col-sm-11">
  <%= form_with(model: user, local: true) do |f| %>

    <% input_disabled ||= false  
       #if input_disabled is not passed to the partial it doesn't crash. 
       # We default it to false 
    %>

    <%= form_errors_for user %>

    <div class="row">
      <div class="col-sm-6">
        <div class="row">

          <div class="form-group col-sm-6">
            <%= f.label :name, class: 'control-label' %>
            <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
          </div>

          <div class="form-group col-sm-6">
            <%= f.label :email, class: 'control-label' %>
            <%= f.text_field :email, class: 'form-control input-sm', disabled: input_disabled %>
          </div>

          <div class="control-group col-sm-12">
            <%= f.label :department_id, class: "control-label" %>
            <%= f.select :department_id, 
                  Department.order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
                  { include_blank: true, multiple: false }, 
                  { class: 'form-control input-sm', disabled: input_disabled } %>
          </div>

          <div class="form-group col-sm-12">
            <%= f.label :position, class: 'control-label' %>
            <%= f.text_field :position, class: 'form-control input-sm', disabled: input_disabled %>
          </div>

        </div>  <!-- /row -->
      </div>  <!-- /col-sm-6 -->

      <div class="col-sm-6">
        <div class="row">

          <div class="form-group col-sm-12">
            <%= f.label :photo, class: 'control-label' %>
            <%= f.file_field :photo, class: 'form-control' %>
          </div>

          <div class="form-group col-sm-12">
            <%= f.label :note, class: 'control-label' %>
            <%= f.text_area :note, :rows => 4, :cols => 50, class: 'form-control input-sm', disabled: input_disabled %>
          </div>
        </div> <!-- /row -->
      </div> <!--/col-sm-6 -->

    </div>  <!-- /row -->


    <hr class="hr-without-top-margin">

    <% if input_disabled %>
      <!-- for "Show" -->
    <% else %>
      <!-- form "New"/"Edit" -->
      <div class="row">
        <%= link_to users_path, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-th-list"></span>
          <%= t("helpers.links.index") %>
        <% end %>

        <%= link_to :back, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-arrow-left"></span>
          <%= t("helpers.links.back") %>
        <% end %>

        <%= f.submit nil, class: 'btn btn-success' %>
      </div> <!-- /row -->
    <% end %>
    
  <% end %>

</div> <!--/col-sm-11-->

app/views/users/_roles.html.erb
<div class="col-sm-12">
  <table id="user-roles-datatable" class="hover cell-border compact" width="100%" 
    data-source="<%= datatables_index_user_roles_path(user_id: @user.id, format: :json) %>",
    data-locale_url="<%= datatables_lang_path(format: :json) %>", 
    data-export_csv_url="<%= export_users_path(format: :csv) %>">
    <thead>
      <tr>
        <th>ID</th>
        <th class="col-sm-3"><%= Role.human_attribute_name(:name) %></th>
        <th class="col-sm-7"><%= Role.human_attribute_name(:activities) %></th>
        <th class="col-sm-1" >Uprawnienie</th>
        <th class="col-sm-1" >Akcje</th>
      </tr>
    </thead>
    <tbody>
       <!--data from JSON -->
    </tbody>
  </table>
</div> <!--/col-sm-12 -->

app/views/users/_user.html.erb
<td class="col-md-5">
  <%= user.name_as_link %>
</td>
<td class="col-md-7">
  <%= user.flat_assigned_projects %>
</td>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-user">
      <div class="panel-heading">
        <div class="panel-title">
          <span class="glyphicon glyphicon-user">&nbsp;</span>
          <span><%=t "pages.user.edit.title"%>:&nbsp;<%= @user.fullname %></span>    
        </div>
      </div>
        <div class="panel-body">
          <div class="col-sm-1">
            <h1><span class="glyphicon glyphicon-edit"></span></h1> 
          </div> <!--/col-sm-1-->

          <%= render 'form', user: @user %>
    
        </div>
    </div> <!-- /panel -->
  </div> <!-- /col-sm-12-->
</div> <!-- /row -->

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center">
        <span class="fa fa-user glyp-index-title" aria-hidden="true"></span>
        <span class="index-title hidden-xs"><%= t '.title' %></span>
<!-- 
        <span class="index-title visible-xs"><%= t '.navbar' %></span>
-->
        <span class="index-title visible-xs"><%= t '.title' %></span>
      </h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <table id="users-datatable" class="hover cell-border" cellspacing="0" width="100%", 
        data-source="<%= users_path(format: :json) %>", 
        data-locale_url="<%= datatables_lang_path(format: :json) %>", 
        data-export_csv_url="<%= export_users_path(format: :csv) %>">
        <thead>
          <tr>
            <th>id</th>
            <th class='col-sm-2'><%= User.human_attribute_name(:name) %></th>
            <th class='col-sm-2'><%= User.human_attribute_name(:department) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:current_sign_in_ip) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:current_sign_in_at) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:last_activity_at) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:password_changed_at) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:deleted_at) %></th>
            <th class='col-sm-1'><%= User.human_attribute_name(:surveys_any) %></th>
          </tr>
        </thead>

        <tbody>
           <!--data from JSON -->
        </tbody>
      </table>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->

</div> <!--/container -->

app/views/users/show.html.erb
<div class="panel-group" id="myaccordion">

  <!-- Dane -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-user">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#myaccordion" href="#collapse_data" >
          <div class="panel-heading">
            <div class="panel-title">
              <span class="glyphicon glyphicon-user">&nbsp;</span>
              <span><%=t ".title"%>:&nbsp;<%= @user.fullname %></span>
              <i class="indicator glyphicon glyphicon-chevron-down  pull-right"></i>
            </div> 
          </div>
        </a>
        <div id="collapse_data" class="panel-collapse collapse in">
          <div class="panel-body">         

            <%= render 'data', input_disabled: true %>

          </div> <!-- /panel-body -->
        </div> <!-- /id="collapse_data" -->
      </div> <!-- /panel -->
    </div> <!-- /col-sm-12-->
  </div> <!-- /row -->

  <% if policy(:user).work? %>
    <%= render partial: "works/works_in_panel", locals: {trackable_type: 'User', trackable_id: @user.id} %>
  <% end %>

  <!-- Roles-->
  <% if policy(:role).index? %>
    <div class="row">
      <div class="col-sm-11 col-sm-offset-1">
        <div class="panel panel-role">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#myaccordion" href="#collapse_user_roles" >
            <div class="panel-heading">
              <div class="panel-title">
                <span class="glyphicon glyphicon-sunglasses">&nbsp;</span>
                <span><%= t ".roles" %></span>
                <i class="indicator glyphicon glyphicon-chevron-right pull-right"></i>
              </div>
            </div>
          </a>
          <div id="collapse_user_roles" class="panel-collapse collapse">
            <div class="panel-body">

              <%= render 'roles' %>

            </div> <!-- /panel-body -->
          </div> <!-- /id="collapse_user_roles" -->
        </div> <!-- /panel -->
      </div> <!-- /col-sm-11 col-sm-offset-1 -->
    </div> <!-- /row -->
  <% end %>

</div> <!-- /class="panel-group" id="myaccordion" -->