config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'export', on: :collection
    get 'datatables_index_role', on: :collection # Displays users for showed role
    patch 'account_off', on: :member
    patch 'account_on', on: :member
  end

  resources :roles do
    get 'export', on: :collection
    get 'datatables_index_user', on: :collection # Displays roles for showed user
    resources :users, only: [:create, :destroy], controller: 'roles/users'
  end    

  resources :surveys do
    get 'export', on: :collection
    get 'send_score', on: :collection 
    get 'show_score', on: :collection 
  end

  resources :works, only: [:index] do
    post 'datatables_index', on: :collection # for User
    post 'datatables_index_trackable', on: :collection # for Trackable
    post 'datatables_index_user', on: :collection # for User
  end

  resources :charts, only: [] do
    get 'departments_by_question_pie', on: :collection
    get 'departments_by_question_column', on: :collection
    get 'departments_sum_pie', on: :collection
    get 'departments_sum_column', on: :collection
    get 'point_files', on: :collection
    get 'xml_miejsce_realizacji_tables', on: :collection
  end

  resources :expositions, except: [:show, :edit, :update]

  get 'datatables/lang'

  get 'static_pages/home'
  get 'static_pages/introduction'
  get 'static_pages/job_1'
  get 'static_pages/job_2'
  get 'static_pages/job_3'
  get 'static_pages/job_4'
  get 'static_pages/job_5'

  root to: 'static_pages#home'

end

app/models/survey.rb
require 'csv'
class Survey < ApplicationRecord
  delegate :url_helpers, to: 'Rails.application.routes'

  belongs_to :user
  has_many :works, as: :trackable


  validates :answer_1_place_1, presence: true
  validates :answer_1_place_2, presence: true
  validates :answer_1_place_3, presence: true
  validates :answer_2_place_1, presence: true
  validates :answer_2_place_2, presence: true
  validates :answer_2_place_3, presence: true
  validates :answer_3_place_1, presence: true
  validates :answer_3_place_2, presence: true
  validates :answer_3_place_3, presence: true
  validates :answer_4_place_1, presence: true
  validates :answer_4_place_2, presence: true
  validates :answer_4_place_3, presence: true

  validate :answer_1
  validate :answer_2
  validate :answer_3
  validate :answer_4


  def log_work(action = '', action_user_id = nil)
    trackable_url = (action == 'destroy') ? nil : "#{url_helpers.role_path(self)}"
    worker_id = action_user_id
    Work.create!(trackable_type: 'Survey', trackable_id: self.id, trackable_url: trackable_url, action: "#{action}", user_id: worker_id, 
      parameters: self.to_json(except: [:user_id], include: {user: {only: [:id, :name, :email]}}))
  end

  def self.to_csv
    CSV.generate(headers: false, col_sep: ';', converters: nil, skip_blanks: false, force_quotes: false) do |csv|
      columns_header = %w(Wypełnił Delegatura Utworzono Aktualizowano)
      csv << columns_header
      all.each do |rec|
        csv << [rec.user.fullname,
                rec.user.department.short,
                rec.created_at.strftime('%Y-%m-%d %H:%M:%S'),
                rec.updated_at.strftime('%Y-%m-%d %H:%M:%S')]
     end
    end.encode('WINDOWS-1250')
  end

  def fullname
    "#{self.user.name} [ostatnia aktualizacja: #{self.updated_at.strftime('%Y-%m-%d %H:%M:%S')}]"
  end

  def number_as_link
    "<a href=#{url_helpers.survey_path(self)}>#{self.user.name}</a>".html_safe
  end

  private

    def answer_1
      analize_value = true
      return if answer_1_place_1.blank? || answer_1_place_2.blank? || answer_1_place_3.blank?
     
      if answer_1_place_1 == answer_1_place_2
        errors.add(:answer_1_place_2, 'Pytanie 1 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_1_place_1 == answer_1_place_3
        errors.add(:answer_1_place_3, 'Pytanie 1 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_1_place_2 == answer_1_place_3
        errors.add(:answer_1_place_3, 'Pytanie 1 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      throw :abort unless analize_value
    end

    def answer_2
      analize_value = true
      return if answer_2_place_1.blank? || answer_2_place_2.blank? || answer_2_place_3.blank?
     
      if answer_2_place_1 == answer_2_place_2
        errors.add(:answer_2_place_2, 'Pytanie 2 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_2_place_1 == answer_2_place_3
        errors.add(:answer_2_place_3, 'Pytanie 2 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_2_place_2 == answer_2_place_3
        errors.add(:answer_2_place_3, 'Pytanie 2 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      throw :abort unless analize_value
    end

    def answer_3
      analize_value = true
      return if answer_3_place_1.blank? || answer_3_place_2.blank? || answer_3_place_3.blank?
     
      if answer_3_place_1 == answer_3_place_2
        errors.add(:answer_3_place_2, 'Pytanie 3 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_3_place_1 == answer_3_place_3
        errors.add(:answer_3_place_3, 'Pytanie 3 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_3_place_2 == answer_3_place_3
        errors.add(:answer_3_place_3, 'Pytanie 3 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      throw :abort unless analize_value
    end

    def answer_4
      analize_value = true
      return if answer_4_place_1.blank? || answer_4_place_2.blank? || answer_4_place_3.blank?
     
      if answer_4_place_1 == answer_4_place_2
        errors.add(:answer_4_place_2, 'Pytanie 4 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_4_place_1 == answer_4_place_3
        errors.add(:answer_4_place_3, 'Pytanie 4 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      if answer_4_place_2 == answer_4_place_3
        errors.add(:answer_4_place_3, 'Pytanie 4 - Określona Delegatura może występić w wynikach poszczególnych pytań tylko raz') 
        analize_value = false 
      end 
      throw :abort unless analize_value
    end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:new, :index, :datatables_index_user, :show_score]
  before_action :set_survey, only: [:show, :edit, :update, :destroy]


  def export
    authorize :survey, :index?
    @data = Survey.joins(:user).merge(User.order(:name)).all
    respond_to do |format|
      format.csv { send_data @data.to_csv, filename: "warsztay_rsp_surveys_#{Time.zone.today.strftime("%Y-%m-%d")}.csv" }
    end
  end

  # GET /surveys/send_score
  def send_score
    authorize :survey, :index?
    SurveyMailer.send_score_email.deliver_now
    flash[:success] = "Wyniki zostały wysłane na pocztę użytkowników."
    redirect_to surveys_url
  end

  # GET /surveys
  # GET /surveys.json
  def index
    authorize :survey, :index?
    respond_to do |format|
      format.html
      format.json { render json: SurveyDatatable.new(params) }
    end
  end

  def datatables_index_user
    respond_to do |format|
      format.json{ render json: UserSurveysDatatable.new(params, { only_for_current_user_id: params[:user_id] }) }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show_score
  end

  def show
    authorize @survey, :show_self?
  end
  # GET /surveys/new
  def new
    if current_user.surveys.any?
      redirect_to survey_path(current_user.surveys.first.id) 
    else
      @survey = Survey.new
      @survey.user_id = current_user.id
      authorize @survey, :new_self?
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  # GET /surveys/1/edit
  def edit
    authorize @survey, :edit_self?
  end

  # POST /surveys
  # POST /surveys.json
  def create
    # @survey = Survey.new(name: params[:survey][:name], note: params[:survey][:note], special: params[:survey][:special],activities: params[:survey][:activities].split)
    @survey = Survey.new(survey_params)
    @survey.user_id = current_user.id
    authorize @survey, :create_self?
    respond_to do |format|
      if @survey.save
        flash[:success] = t('activerecord.successfull.messages.created', data: @survey.fullname)
        @survey.log_work('create', current_user.id)
        format.html { redirect_to @survey }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    authorize @survey, :update_self?
    respond_to do |format|
      # if @survey.update(name: params[:survey][:name], note: params[:survey][:note], special: params[:survey][:special],activities: params[:survey][:activities].split)
      if @survey.update(survey_params)
        flash[:success] = t('activerecord.successfull.messages.updated', data: @survey.fullname)
        @survey.log_work('update', current_user.id)
        format.html { redirect_to @survey }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    # @survey.destroy
    # respond_to do |format|
    #   flash[:success] = "Survey destroyed!"
    #   format.html { redirect_to surveys_url }
    #   format.json { head :no_content }
    # end
    authorize @survey, :destroy_self?
    if @survey.destroy
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @survey.fullname)
      redirect_to surveys_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @survey.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit( :answer_1_place_1, :answer_1_place_2, :answer_1_place_3,
                                      :answer_2_place_1, :answer_2_place_2, :answer_2_place_3,
                                      :answer_3_place_1, :answer_3_place_2, :answer_3_place_3,
                                      :answer_4_place_1, :answer_4_place_2, :answer_4_place_3, :note, :user_id)
    end
end

app/views/surveys/_data_note.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.note.fieldset_title') %></legend>

  <div class="row">
    <div class="form-group col-sm-12">
<!-- 
      <p><strong><%#= Survey.human_attribute_name(:note) %></strong></p>

-->    <%= text_with_break_line(@survey.note) %>
    </div>
  </div> <!--/row -->
</fieldset>

app/views/surveys/_data_question_1.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_1.fieldset_title') %></legend>

  <div class="row">
    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_1.body') %></p>
    </div>

    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_1_place_1) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_1_place_1).name unless partial_data.answer_1_place_1.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_1_place_2) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_1_place_2).name unless partial_data.answer_1_place_2.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_1_place_3) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_1_place_3).name unless partial_data.answer_1_place_3.blank? %></p>
    </div>
  </div> <!--/row -->
</fieldset>

app/views/surveys/_data_question_3.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_3.fieldset_title') %></legend>

  <div class="row">
    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_3.body') %></p>
    </div>

    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_3_place_1) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_3_place_1).name unless partial_data.answer_3_place_1.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_3_place_2) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_3_place_2).name unless partial_data.answer_3_place_2.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_3_place_3) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_3_place_3).name unless partial_data.answer_3_place_3.blank? %></p>
    </div>
  </div> <!--/row -->
</fieldset>

app/views/surveys/_data_question_4.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_4.fieldset_title') %></legend>

  <div class="row">
    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_4.body') %></p>
    </div>

    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_4_place_1) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_4_place_1).name unless partial_data.answer_4_place_1.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_4_place_2) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_4_place_2).name unless partial_data.answer_4_place_2.blank? %></p>
    </div>
    <div class="form-group col-sm-12">
      <p><strong><%= partial_data.class.human_attribute_name(:answer_4_place_3) %></strong>:&nbsp;
      <%= Department.find(partial_data.answer_4_place_3).name unless partial_data.answer_4_place_3.blank? %></p>
    </div>
  </div> <!--/row -->
</fieldset>

app/views/surveys/_form.html.erb
<div class="col-sm-11">
  <%= form_with(model: survey, local: true) do |f| %>

    <% input_disabled ||= false  
       #if input_disabled is not passed to the partial it doesn't crash. 
       # We default it to false 
    %>

    <%= form_errors_for survey %>

    <%= render 'form_question_1', f: f, survey: survey, input_disabled: input_disabled %>
    <%= render 'form_question_2', f: f, survey: survey, input_disabled: input_disabled %>
    <%= render 'form_question_3', f: f, survey: survey, input_disabled: input_disabled %>
    <%= render 'form_question_4', f: f, survey: survey, input_disabled: input_disabled %>
    <%= render 'form_note',       f: f, survey: survey, input_disabled: input_disabled %>


    <hr class="hr-without-top-margin">

    <% if input_disabled %>
      <!-- for "Show" -->
    <% else %>
      <!-- form "New"/"Edit" -->
      <div class="row">

        <%= link_to :back, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-arrow-left"></span>
          <%= t("helpers.links.back") %>
        <% end %>

        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div> <!-- /row -->
    <% end %>
    
  <% end %>

</div> <!--/col-sm-11-->

app/views/surveys/_form_note.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.note.fieldset_title') %></legend>
    <div class="form-group col-sm-12">
      <%= f.text_area :note, :rows => 4, :cols => 50, class: 'form-control input-sm', disabled: input_disabled %>
    </div>
</fieldset>

app/views/surveys/_form_question_1.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_1.fieldset_title') %></legend>

    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_1.body') %></p>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_1_place_1, class: "control-label" %>
      <%= f.select :answer_1_place_1, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_1_place_2, class: "control-label" %>
      <%= f.select :answer_1_place_2, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_1_place_3, class: "control-label" %>
      <%= f.select :answer_1_place_3, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
</fieldset>

app/views/surveys/_form_question_2.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_2.fieldset_title') %></legend>

    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_2.body') %></p>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_2_place_1, class: "control-label" %>
      <%= f.select :answer_2_place_1, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_2_place_2, class: "control-label" %>
      <%= f.select :answer_2_place_2, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_2_place_3, class: "control-label" %>
      <%= f.select :answer_2_place_3, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
</fieldset>

app/views/surveys/_form_question_3.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_3.fieldset_title') %></legend>

    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_3.body') %></p>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_3_place_1, class: "control-label" %>
      <%= f.select :answer_3_place_1, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_3_place_2, class: "control-label" %>
      <%= f.select :answer_3_place_2, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_3_place_3, class: "control-label" %>
      <%= f.select :answer_3_place_3, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
</fieldset>

app/views/surveys/_form_question_4.html.erb
<fieldset class="my-fieldset">
  <legend class="my-fieldset"><%= t('surveys.question_4.fieldset_title') %></legend>

    <div class="form-group col-sm-12">
      <p><%= t('surveys.question_4.body') %></p>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_4_place_1, class: "control-label" %>
      <%= f.select :answer_4_place_1, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_4_place_2, class: "control-label" %>
      <%= f.select :answer_4_place_2, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
    <div class="control-group col-sm-12">
      <%= f.label :answer_4_place_3, class: "control-label" %>
      <%= f.select :answer_4_place_3, 
            Department.where.not(id: [1, 2, 3, @current_user.department_id]).order(:short).collect {|p| [ "#{p.short}, #{p.name}", p.id ]},
            { include_blank: true, multiple: false }, 
            { class: 'form-control input-sm', disabled: input_disabled } %>
    </div>
</fieldset>

app/views/surveys/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-survey">
      <div class="panel-heading">
        <div class="panel-title">
          <span class="fa fa-list-ol">&nbsp;</span>
          <span><%=t ".title"%>:&nbsp;<%= @survey.fullname %></span>    
        </div>
      </div>
        <div class="panel-body">
          <div class="col-sm-1">
            <h1><span class="glyphicon glyphicon-edit"></span></h1> 
          </div> <!--/col-sm-1-->

          <%= render 'form', survey: @survey %>
    
        </div>
    </div> <!-- /panel -->
  </div> <!-- /col-sm-12-->
</div> <!-- /row -->

app/views/surveys/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center">
        <span class="fa fa-list-ol glyp-index-title" aria-hidden="true"></span>
        <span class="index-title hidden-xs"><%= t '.title' %></span>
<!-- 
        <span class="index-title visible-xs"><%= t '.navbar' %></span>
-->
        <span class="index-title visible-xs"><%= t '.title' %></span>
      </h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <table id="surveys-datatable" class="hover cell-border" cellspacing="0" width="100%", 
        data-source="<%= surveys_path(format: :json) %>", 
        data-locale_url="<%= datatables_lang_path(format: :json) %>", 
        data-export_csv_url="<%= export_surveys_path(format: :csv) %>">
        <thead>
          <tr>
            <th>id</th>
            <th><%= Survey.human_attribute_name(:user) %></th>
            <th><%= Survey.human_attribute_name(:created_at) %></th>
            <th><%= Survey.human_attribute_name(:updated_at) %></th>
          </tr>
        </thead>

        <tbody>
           <!--data from JSON -->
        </tbody>
      </table>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->

  <div class="row">
    <div class="col-sm-12">

      <% enabled_disabled = (Survey.all.count < Role.find(5).users.count) ? "disabled" : "" %> 
      <%= link_to send_score_surveys_path, class: "btn btn-warning btn-lg #{enabled_disabled}" do %>
        <span class="fa fa-envelope"></span>&nbsp;<%= t("helpers.links.send_email") %>
      <% end %>

    </div>
  </div>

  <%= render partial: "data_charts" %>

</div> <!--/container -->

app/views/surveys/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center">
        <span class="fa fa-list-ol glyp-index-title" aria-hidden="true"></span>
        <span class="index-title"><%= t '.title' %></span>
      </h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->

  <%= render partial: "data_question_1", locals: {partial_data: @survey} %>
  <%= render partial: "data_question_2", locals: {partial_data: @survey} %>
  <%= render partial: "data_question_3", locals: {partial_data: @survey} %>
  <%= render partial: "data_question_4", locals: {partial_data: @survey} %>
  <%= render partial: "data_note",       locals: {partial_data: @survey} %>

  <div class="row">
    <div class="col-sm-12">

      <%= link_to root_path, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-arrow-left"></span>
        <%= t("helpers.links.back") %>
      <% end %>

      <% if policy(@survey).edit_self? %>
        <% enabled_disabled = (Survey.all.count >= Role.find(5).users.count) ? "disabled" : "" %>
        <%= link_to edit_survey_path(@survey), class: "btn btn-primary #{enabled_disabled}" do %>
          <span class="glyphicon glyphicon-edit"></span>
          <%= t("helpers.links.edit") %>
        <% end %>
      <% end %>

    </div> <!--/col-sm-12 -->
  </div> <!-- /row -->

  <% if Survey.all.count >= Role.find(5).users.count %>
    <%= render partial: "data_charts" %>
  <% end %>

</div> <!--/container -->

app/views/surveys/show_score.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center">
        <span class="fa fa-poll glyp-index-title" aria-hidden="true"></span>
        <span class="index-title hidden-xs"><%= t '.title' %></span>
<!-- 
        <span class="index-title visible-xs"><%= t '.navbar' %></span>
-->
        <span class="index-title visible-xs"><%= t '.title' %></span>
      </h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->

<div class="container-fluid">

      <%= render partial: "data_charts" %>

</div> <!--/container -->