config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'export', on: :collection
    get 'datatables_index_role', on: :collection # Displays users for showed role
    patch 'account_off', on: :member
    patch 'account_on', on: :member
  end

  resources :roles do
    get 'export', on: :collection
    get 'datatables_index_user', on: :collection # Displays roles for showed user
    resources :users, only: [:create, :destroy], controller: 'roles/users'
  end    

  resources :surveys do
    get 'export', on: :collection
    get 'send_score', on: :collection 
    get 'show_score', on: :collection 
  end

  resources :works, only: [:index] do
    post 'datatables_index', on: :collection # for User
    post 'datatables_index_trackable', on: :collection # for Trackable
    post 'datatables_index_user', on: :collection # for User
  end

  resources :charts, only: [] do
    get 'departments_by_question_pie', on: :collection
    get 'departments_by_question_column', on: :collection
    get 'departments_sum_pie', on: :collection
    get 'departments_sum_column', on: :collection
    get 'point_files', on: :collection
    get 'xml_miejsce_realizacji_tables', on: :collection
  end

  resources :expositions, except: [:show, :edit, :update]

  get 'datatables/lang'

  get 'static_pages/home'
  get 'static_pages/introduction'
  get 'static_pages/job_1'
  get 'static_pages/job_2'
  get 'static_pages/job_3'
  get 'static_pages/job_4'
  get 'static_pages/job_5'

  root to: 'static_pages#home'

end

app/models/role.rb
class Role < ApplicationRecord
  delegate :url_helpers, to: 'Rails.application.routes'

  # relations
  has_and_belongs_to_many :users
  has_many :works, as: :trackable

  # validates
  validates :name, presence: true,
                    length: { in: 1..100 },
                    uniqueness: { case_sensitive: false }

  def log_work(action = '', action_user_id = nil)
    trackable_url = (action == 'destroy') ? nil : "#{url_helpers.role_path(self)}"
    worker_id = action_user_id
    Work.create!(trackable_type: 'Role', trackable_id: self.id, trackable_url: trackable_url, action: "#{action}", user_id: worker_id, 
      parameters: self.to_json())
  end


  def fullname
    "#{name}"
  end

  def name_as_link
    "<a href=#{url_helpers.role_path(self)}>#{self.name}</a>".html_safe
  end


  def role_link_add_remove(user, has_role)
    if has_role
      "<div style='text-align: center'><button ajax-path='#{url_helpers.role_user_path(role_id: self.id, id: user)}' ajax-method='DELETE' class='btn btn-xs btn-danger glyphicon glyphicon-minus'></button></div>".html_safe
    else
      "<div style='text-align: center'><button ajax-path='#{url_helpers.role_users_path(role_id: self.id, id: user)}' ajax-method='POST' class='btn btn-xs btn-success glyphicon glyphicon-plus'></button></div>".html_safe
    end
  end

end

app/controllers/roles/users_controller.rb
class Roles::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 
    role.users << user if role.present? && user.present?
    head :ok
  end

  def destroy
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 
    user.roles.delete(role) if role.present? && user.present?
    head :no_content
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index_user]
  before_action :set_role, only: [:show, :edit, :update, :destroy]


  def export
  end

  # GET /roles
  # GET /roles.json
  def index
    authorize :role, :index?
    respond_to do |format|
      format.html
      format.json { render json: RoleDatatable.new(params) }
    end
  end

  def datatables_index_user
    respond_to do |format|
      format.json{ render json: UserRolesDatatable.new(params, { only_for_current_user_id: params[:user_id] }) }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    authorize @role, :show?
  end

  # GET /roles/new
  def new
    @role = Role.new
    authorize @role, :new?
  end

  # GET /roles/1/edit
  def edit
    authorize @role, :edit?
  end

  # POST /roles
  # POST /roles.json
  def create
    # @role = Role.new(name: params[:role][:name], note: params[:role][:note], special: params[:role][:special],activities: params[:role][:activities].split)
    @role = Role.new(role_params)
    authorize @role, :create?
    respond_to do |format|
      if @role.save
        flash[:success] = t('activerecord.successfull.messages.created', data: @role.fullname)
        @role.log_work('create', current_user.id)
        format.html { redirect_to @role }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    authorize @role, :update?
    respond_to do |format|
      # if @role.update(name: params[:role][:name], note: params[:role][:note], special: params[:role][:special],activities: params[:role][:activities].split)
      if @role.update(role_params)
        flash[:success] = t('activerecord.successfull.messages.updated', data: @role.fullname)
        @role.log_work('update', current_user.id)
        format.html { redirect_to @role }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    # @role.destroy
    # respond_to do |format|
    #   flash[:success] = "Role destroyed!"
    #   format.html { redirect_to roles_url }
    #   format.json { head :no_content }
    # end
    authorize @role, :destroy?
    if @role.destroy
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @role.fullname)
      redirect_to roles_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @role.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      # params.require(:role).permit(:name, :note, :activities, :special)

      # activities_array = params[:role][:activities].split || []
      # params.require(:role).permit(:name, :note, :special).merge(activities: activities_array)

      params.require(:role).permit(:name, :note, :special, :activities).tap do |parameters|
        parameters[:activities] = parameters[:activities].try(:split)
      end
    end
end

app/views/roles/_data.html.erb
<div class="col-sm-11 col-sm-offset-1">
  <% input_disabled ||= false  
     #if input_disabled is not passed to the partial it doesn't crash. 
     # We default it to false 
  %>

  <%= form_errors_for @role %>

  <div class="row">
    <div class="col-sm-6">
      <div class="row">

        <div class="form-group col-sm-12">
          <p><strong><%= Role.human_attribute_name(:name) %></strong></p>
          <%= @role.name %>
        </div>

      </div>  <!-- /row -->
    </div>  <!-- /col-sm-6 -->

    <div class="col-sm-6">
      <div class="row">
        <div class="form-group col-sm-12">
          <p><strong><%= Role.human_attribute_name(:note) %></strong></p>
          <%= text_with_break_line(@role.note) %>
        </div>
      </div>
    </div> <!--/col-sm-6 -->
  </div>  <!-- /row -->

  <div class="row">
    <div class="col-sm-12">
      <div class="row">

        <div class="form-group col-sm-12">
          <p><strong><%= Role.human_attribute_name(:activities) %></strong></p>
          <%= @role.activities %>
        </div>

      </div> <!-- /row -->
    </div> <!--/col-sm-12 -->
  </div>  <!-- /row -->

  <hr class="hr-without-top-margin">

  <% if input_disabled %>
    <!-- for "Show" -->
    <div class="row">

      <%= link_to roles_path, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-th-list"></span>
        <%= t("helpers.links.index") %>
      <% end %>

      <% if policy(@role).destroy? %>
        <%= link_to role_path(@role),
                            method: :delete,
                            data: { confirm: t('helpers.links.confirm_destroy', data: @role.name) }, 
                            class: "btn btn-danger" do %>
          <span class="glyphicon glyphicon-trash"></span>
          <%= t("helpers.links.destroy") %>
        <% end %>
      <% end %>

      <% if policy(@role).edit? %>
        <%= link_to edit_role_path(@role), class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-edit"></span>
          <%= t("helpers.links.edit") %>
        <% end %>
      <% end %>

    </div> <!-- /row -->
  <% else %>
    <!-- form "New"/"Edit" -->
  <% end %>

</div> <!--/col-sm-11 col-sm-offset-1-->    

app/views/roles/_form.html.erb
<div class="col-sm-11">
  <%= form_with(model: role, local: true) do |f| %>

    <% input_disabled ||= false  
       #if input_disabled is not passed to the partial it doesn't crash. 
       # We default it to false 
    %>

    <%= form_errors_for role %>

    <div class="row">
      <div class="col-sm-6">
        <div class="row">

          <div class="form-group required col-sm-12">
            <%= f.label :name, class: 'control-label' %>
            <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
          </div>

        </div>  <!-- /row -->
      </div>  <!-- /col-sm-6 -->


      <div class="col-sm-6">
        <div class="row">
          <div class="form-group col-sm-12">
            <%= f.label :note, class: 'control-label' %>
            <%= f.text_area :note, :rows => 4, :cols => 50, class: 'form-control input-sm', disabled: input_disabled %>
          </div>
        </div> <!-- /row -->
      </div> <!--/col-sm-6 -->

    </div>  <!-- /row -->

    <div class="row">
      <div class="col-sm-12">
        <div class="row">

          <div class="form-group col-sm-12">
            <%= f.label :activities %>
            <%= f.text_field :activities, class: 'form-control input-sm', disabled: input_disabled %>
          </div>

        </div> <!-- /row -->
      </div> <!--/col-sm-12 -->
    </div>  <!-- /row -->


    <hr class="hr-without-top-margin">

    <% if input_disabled %>
      <!-- for "Show" -->
    <% else %>
      <!-- form "New"/"Edit" -->
      <div class="row">

        <%= link_to roles_path, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-th-list"></span>
          <%= t("helpers.links.index") %>
        <% end %>
        <%= link_to :back, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-arrow-left"></span>
          <%= t("helpers.links.back") %>
        <% end %>

        <%= f.submit nil, class: 'btn btn-success' %>
      </div> <!-- /row -->
    <% end %>
    
  <% end %>

</div> <!--/col-sm-11-->

app/views/roles/_role.html.erb
<td class="col-md-2">
  <%= role.name_as_link %>
</td>
<td class="col-md-1">
  <%= role.special %>
</td>
<td class="col-md-6">
  <%= role.activities %>
</td>
<td class="col-md-3">
  <%= truncate(role.note, length: 50) %>
</td>
<!--
<td>
  <%#= link_to("Delete role", role_path(role), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs-danger') %>
</td>
-->

app/views/roles/_users.html.erb
<div class="col-sm-12">
  <table id="role-users-datatable" class="hover cell-border compact" width="100%" 
    data-source="<%= datatables_index_role_users_path(role_id: @role.id, format: :json) %>",
    data-locale_url="<%= datatables_lang_path(format: :json) %>", 
    data-export_csv_url="<%= export_roles_path(format: :csv) %>">
    <thead>
      <tr>
        <th>ID</th>
        <th class="col-sm-4"><%= User.human_attribute_name(:name) %></th>
        <th class="col-sm-6"><%= User.human_attribute_name(:note) %></th>
        <th class="col-sm-1" >Uprawnienie</th>
        <th class="col-sm-1" >Akcje</th>
      </tr>
    </thead>
    <tbody>
       <!--data from JSON -->
    </tbody>
  </table>
</div> <!--/col-sm-12 -->

app/views/roles/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-role">
      <div class="panel-heading">
        <div class="panel-title">
          <span class="glyphicon glyphicon-sunglasses">&nbsp;</span>
          <span><%=t "pages.role.edit.title"%>:&nbsp;<%= @role.fullname %></span>    
        </div>
      </div>
        <div class="panel-body">
          <div class="col-sm-1">
            <h1><span class="glyphicon glyphicon-edit"></span></h1> 
          </div> <!--/col-sm-1-->

          <%= render 'form', role: @role %>
    
        </div>
    </div> <!-- /panel -->
  </div> <!-- /col-sm-12-->
</div> <!-- /row -->

app/views/roles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center">
        <span class="glyphicon glyphicon-sunglasses glyp-index-title" aria-hidden="true"></span>
        <span class="index-title hidden-xs"><%= t '.title' %></span>
<!-- 
        <span class="index-title visible-xs"><%= t '.navbar' %></span>
-->
        <span class="index-title visible-xs"><%= t '.title' %></span>
      </h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <table id="roles-datatable" class="hover cell-border" cellspacing="0" width="100%", 
        data-source="<%= roles_path(format: :json) %>", 
        data-locale_url="<%= datatables_lang_path(format: :json) %>", 
        data-export_csv_url="<%= export_roles_path(format: :csv) %>">
        <thead>
          <tr>
            <th>id</th>
            <th class='col-sm-4'><%= Role.human_attribute_name(:name) %></th>
            <th class='col-sm-4'><%= Role.human_attribute_name(:note) %></th>
            <th class='col-sm-4'><%= Role.human_attribute_name(:activities) %></th>
          </tr>
        </thead>

        <tbody>
           <!--data from JSON -->
        </tbody>
      </table>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->

</div> <!--/container -->

app/views/roles/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-role">
      <div class="panel-heading">
        <div class="panel-title">
          <span class="glyphicon glyphicon-sunglasses">&nbsp;</span>
          <span><%=t "pages.role.new.title" %></span>
        </div>
      </div>
        <div class="panel-body">
          <div class="col-sm-1">
            <h1><span class="glyphicon glyphicon-plus"></span></h1> 
          </div> <!--/col-sm-1-->

          <%= render 'form', role: @role %>
    
        </div>
    </div> <!-- /panel -->
  </div> <!-- /col-sm-12-->
</div> <!-- /row -->

app/views/roles/show.html.erb
<div class="panel-group" id="myaccordion">

  <!-- Dane -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-role">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#myaccordion" href="#collapse_data" >
          <div class="panel-heading">
            <div class="panel-title">
              <span class="glyphicon glyphicon-sunglasses">&nbsp;</span>
              <span><%=t ".title"%>:&nbsp;<%= @role.fullname %></span>
              <i class="indicator glyphicon glyphicon-chevron-down  pull-right"></i>
            </div> 
          </div>
        </a>
        <div id="collapse_data" class="panel-collapse collapse in">
          <div class="panel-body">         

            <%= render 'data', input_disabled: true %>

          </div> <!-- /panel-body -->
        </div> <!-- /id="collapse_data" -->
      </div> <!-- /panel -->
    </div> <!-- /col-sm-12-->
  </div> <!-- /row -->

  <% if policy(:user).work? %>
    <%= render partial: "works/works_in_panel", locals: {trackable_type: 'Role', trackable_id: @role.id} %>
  <% end %>

  <!-- Roles-->
  <% if policy(:user).index? %>
    <div class="row">
      <div class="col-sm-11 col-sm-offset-1">
        <div class="panel panel-user">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#myaccordion" href="#collapse_role_users" >
            <div class="panel-heading">
              <div class="panel-title">
                <span class="glyphicon glyphicon-user">&nbsp;</span>
                <span><%= t ".users" %></span>
                <i class="indicator glyphicon glyphicon-chevron-right pull-right"></i>
              </div>
            </div>
          </a>
          <div id="collapse_role_users" class="panel-collapse collapse">
            <div class="panel-body">

              <%= render 'users' %>

            </div> <!-- /panel-body -->
          </div> <!-- /id="collapse_role_users" -->
        </div> <!-- /panel -->
      </div> <!-- /col-sm-11 col-sm-offset-1 -->
    </div> <!-- /row -->
  <% end %>

</div> <!-- /class="panel-group" id="myaccordion" -->