config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users do
    get 'export', on: :collection
    get 'datatables_index_role', on: :collection # Displays users for showed role
    patch 'account_off', on: :member
    patch 'account_on', on: :member
  end

  resources :roles do
    get 'export', on: :collection
    get 'datatables_index_user', on: :collection # Displays roles for showed user
    resources :users, only: [:create, :destroy], controller: 'roles/users'
  end    

  resources :surveys do
    get 'export', on: :collection
    get 'send_score', on: :collection 
    get 'show_score', on: :collection 
  end

  resources :works, only: [:index] do
    post 'datatables_index', on: :collection # for User
    post 'datatables_index_trackable', on: :collection # for Trackable
    post 'datatables_index_user', on: :collection # for User
  end

  resources :charts, only: [] do
    get 'departments_by_question_pie', on: :collection
    get 'departments_by_question_column', on: :collection
    get 'departments_sum_pie', on: :collection
    get 'departments_sum_column', on: :collection
    get 'point_files', on: :collection
    get 'xml_miejsce_realizacji_tables', on: :collection
  end

  resources :expositions, except: [:show, :edit, :update]

  get 'datatables/lang'

  get 'static_pages/home'
  get 'static_pages/introduction'
  get 'static_pages/job_1'
  get 'static_pages/job_2'
  get 'static_pages/job_3'
  get 'static_pages/job_4'
  get 'static_pages/job_5'

  root to: 'static_pages#home'

end

app/views/layouts/_errors.html.erb
<% content_for :form_errors do %>
  <div id="error_explanation" class="panel panel-danger">
    <div class="panel-heading">
      <div class="panel-title">
        <span class="glyphicon glyphicon-flash">&nbsp;Uwaga!</span>

        <button type="button" class="close" data-target="#error_explanation" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>

      </div> 
    </div>

    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><h5><%= msg %></h5></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>
 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class='col-sm-6'>
      <h4><%= t('.brand') %></h4>
      <h4><%= t('.brand_address_1') %></h4>
      <h4><%= t('.brand_address_2') %></h4>
      <br>
      <h5><%= t('.brand_note') %></h5>
      <hr class="visible-xs">
    </div>

    <div class='col-sm-3'>
      <h5><%= t('.contact') %></h5>
        <ul><h5><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;<%= mail_to t('.contact_mail') %></h5></ul>
        <ul><h5><span class="fa fa-phone"></span>&nbsp;&nbsp;<%= link_to t('.contact_phone'), "tel:#{t('.contact_phone')}" %></h5></ul>
        <ul><h5><span class="fa fa-fax"></span>&nbsp;&nbsp;<%= link_to t('.contact_fax'), "tel:#{t('.contact_fax')}" %></h5></ul>
      <hr class="visible-xs">
    </div>

    <div class="col-sm-3">
      <h5><%= t('.links') %></h5>
        <ul><h5><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('UKE', 'http://uke.gov.pl', target: "_blank") %></h5></ul>
        <ul><h5><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('Facebook', 'https://web.facebook.com/UrzadKomunikacjiElektronicznej', target: "_blank") %></h5></ul>
        <ul><h5><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('Twitter', 'https://twitter.com/uke2uke', target: "_blank") %></h5></ul>
      <hr class="visible-xs">

      <h6 class="pull-right">&copy; 2019 UKE - Biuro Informatyki</h6>

    </div>
  </div>  <!-- /row -->

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand hidden-xs" style="margin-top: 15px; max-width: 400px;display: inline-block;">
        <%= link_to( image_tag( t('logo_file'), alt: 'app logo', :class => "img img-responsive" ), root_path ) %>
      </div>
      <div class="navbar-brand visible-xs" style="max-width: 260px;display: inline-block;">
        <%= link_to( image_tag( t('logo_file'), alt: 'app logo', :class => "img img-responsive" ), root_path ) %>
      </div>

    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <nav>

        <ul class="nav navbar-nav navbar-left">
          <%= render 'layouts/navigation_left_links' %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/navigation_right_links' %>
        </ul>

      </nav>
    </div>

    <hr class="hr-without-all-margin">

  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= flash_class_name(name) %>" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
      </button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_left_links.html.erb
<% if user_signed_in? %>

	<li><%= link_to static_pages_introduction_path do %>
	  <span class="fa fa-info-circle"></span>&nbsp;<%=t ".introduction" %>
	  <% end %>
	</li>

	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".jobs" %> <span class="caret"></span></a>

	  <ul class="dropdown-menu">

			<li><%= link_to static_pages_job_1_path do %>
			  <span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".job_1" %>
			  <% end %>
			</li>

			<li><%= link_to static_pages_job_2_path do %>
			  <span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".job_2" %>
			  <% end %>
			</li>

			<li><%= link_to static_pages_job_3_path do %>
			  <span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".job_3" %>
			  <% end %>
			</li>

			<li><%= link_to static_pages_job_4_path do %>
			  <span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".job_4" %>
			  <% end %>
			</li>

			<li><%= link_to static_pages_job_5_path do %>
			  <span class="glyphicon glyphicon-saved"></span>&nbsp;<%=t ".job_5" %>
			  <% end %>
			</li>

	  </ul>
	</li>


  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-ellipsis-v"></span>&nbsp;<%=t ".extras" %> <span class="caret"></span></a>

    <ul class="dropdown-menu">

      <% if policy(:survey).new_self? %>
        <li><%= link_to new_survey_path do %>
          <span class="fa fa-list-ol"></span>&nbsp;<%=t ".survey" %>
          <% end %>
        </li>
      <% end %>

      <% if Survey.all.count >= Role.find(5).users.count %>
        <li><%= link_to show_score_surveys_path do %>
          <span class="fa fa-poll"></span>&nbsp;<%=t ".surveys_score" %>
          <% end %>
        </li>
      <% end %>

      <li><%= link_to expositions_path do %>
        <span class="fa fa-camera"></span>&nbsp;<%=t ".expositions" %>
        <% end %>
      </li>

    </ul>
  </li>

  
<% end %>

app/views/layouts/_navigation_right_links.html.erb
<% if user_signed_in? %>

  <% if policy(:user).index? || policy(:role).index? || policy(:survey).index? || policy(:work).index? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-tools"></span>&nbsp;<%=t ".management" %> <span class="caret"></span></a>

      <ul class="dropdown-menu">

        <% if policy(:user).index? %>
          <li><%= link_to users_path do %>
            <span class="glyphicon glyphicon-user"></span>&nbsp;<%=t ".users" %>
            <% end %>
          </li>
        <% end %>

        <% if policy(:role).index? %>
          <li><%= link_to roles_path do %>
            <span class="glyphicon glyphicon-sunglasses"></span>&nbsp;<%=t ".roles" %>
            <% end %>
          </li>
        <% end %>

        <% if policy(:survey).index? %>
          <li><%= link_to surveys_path do %>
            <span class="fa fa-list-ol"></span>&nbsp;<%=t ".surveys" %>
            <% end %>
          </li>
        <% end %>

        <% if policy(:work).index? %>
          <li><%= link_to works_path do %>
            <span class="fa fa-history"></span>&nbsp;<%=t ".works" %>
            <% end %>
          </li>
        <% end %>

      </ul>
    </li>
  <% end %>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></span>&nbsp;<span><%= image_tag(current_user.photo, height: 36) %></span>&nbsp;&nbsp;<%= current_user.name %> <span class="caret"></span></a>

    <ul class="dropdown-menu">

      <li><%= link_to edit_user_registration_path do %>
        <span class="fa fa-cog"></span>&nbsp;<%=t "devise.link_to.edit_registration" %>
        <% end %>
      </li>
      <li><%= link_to destroy_user_session_path, :method=>'delete' do %>
        <span class="glyphicon glyphicon-log-out"></span>&nbsp;<%=t "devise.link_to.sign_out" %>
        <% end %>
      </li>

    </ul>
  </li>

<% else %>
  <%# if request_from_the_security_area? %>
    <li><%= link_to new_user_session_path do %>
      <span class="glyphicon glyphicon-log-in"></span>&nbsp;<%=t "devise.link_to.sign_in" %>
      <% end %>
    </li>
  <%# end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UKE Warsztaty" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "UKE Warsztaty" %>">

    <!-- IE Compatible -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'shortcut icon', :type => "image/x-icon" %>

    <%= yield(:javascript) %> 

    <!-- Bootstrap Js CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    <script src="http://code.highcharts.com/modules/exporting.js"></script>
    <!-- optional -->
    <script src="http://code.highcharts.com/modules/offline-exporting.js"></script>
    <script src="http://code.highcharts.com/modules/export-data.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>

  </head>

  <body>
    <div class="content">
      <%= render 'layouts/header', cached: true %>
      <main>
        <%= render 'layouts/messages' %>
        <%= yield(:form_errors) %>       
        <%= yield %>
      </main>
    </div>
    <%= render 'layouts/footer', cached: true %>
  </body>
</html>

app/views/layouts/my_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag "foundation_emails" %>

    <style>

      .body {
        background: #f3f3f3 !important;
      }

      .h6-small {
        @extend .h6;
        font-size: 12px;
      }

      .hr-brand {
        @extend .hr;
        background-color: #C7D540 !important;
        color: #C7D540 !important;
        border: solid 2px #C7D540 !important;
      }

      .hr-brand2 {
        @extend .hr;
        background-color: #ddd !important;
        color: #ddd !important;
        border: solid 1px #ddd !important;
      }


    </style>

  </head>

  <body>
    <table class="body" data-made-with-foundation>
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            <%= yield %>
          </center>
        </td>
      </tr>
    </table>
  </body>
</html>

app/views/layouts/survey_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag "foundation_emails" %>

    <style>

      .body {
        background: #f3f3f3 !important;
      }

      .h6-small {
        @extend .h6;
        font-size: 12px;
      }

      .hr-brand {
        @extend .hr;
        background-color: #C7D540 !important;
        color: #C7D540 !important;
        border: solid 2px #C7D540 !important;
      }

      .hr-brand2 {
        @extend .hr;
        background-color: #ddd !important;
        color: #ddd !important;
        border: solid 1px #ddd !important;
      }


    </style>

  </head>

  <body>
    <table class="body" data-made-with-foundation>
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            <%= yield %>
          </center>
        </td>
      </tr>
    </table>
  </body>
</html>